### ISSUE TITLE
Deployment in circle

### ISSUE THREAD

**Issue by yorkie** [weflex/product-development-guide#2]
I think we should leave 1-2 days to deploy major stuff to production in every end of development circle, because I feel it gets worse a bit in this week, and we are still doing concern the v1.4 and v1.5, this might be a problem now I guess.

@weflex/owners may I ask someone to write a PR to update the workflow for the above described issue, thank you.

**Comment by scottoasis** [comment]
Resolved in https://github.com/weflex/product-development-guide/pull/3
